website/models.py
from . import db 
from flask_login import UserMixin
from flask_login.mixins import UserMixin

# Create models for blogposts and users to store in the database
class Blogpost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    date_posted = db.Column(db.DateTime)
    published = db.Column(db.Boolean)
    content = db.Column(db.Text)
    slug = db.Column(db.String(50))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(100))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

DB_NAME = "blog.db"
UPLOAD_FOLDER = 'static/img/blog'

# Instantiate the database
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

    db.init_app(app)
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Blogpost

    create_database(app)

    # Create LoginManager for to save user credentials
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
import os
import uuid
import re
from flask import Blueprint, url_for, redirect, render_template, flash, request
from .models import User, Blogpost
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, current_user
from . import db
from datetime import datetime
from os import error, path
from werkzeug.utils import secure_filename

auth = Blueprint('auth', __name__)


@auth.route('/blog/signup/', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')

        user = User.query.filter_by(username=username).first()

        if user:
            flash('NO', category='error')
        elif password != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(username=username,
                            password=generate_password_hash(password, method='sha256'))

            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')

            return redirect(url_for('auth.login'))

    return render_template('/blog/signup.html', user=current_user)


@auth.route('/blog/login/', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        flash('You are already logged in', category='error')
        return redirect(url_for('auth.blog'))

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()

        if user:
            if user.id != 6:
                flash('Cannot log into this account', category='error')
                return redirect(url_for('auth.blog'))

            if check_password_hash(user.password, password):
                flash('You are now logged in.', 'success')
                login_user(user, remember=True)

                return redirect(url_for('auth.blog'))
            else:
                flash('Incorrect password.', 'danger')
        else:
            flash('User does not exist', category='error')

    return render_template('/blog/login.html', user=current_user)


@auth.route('/blog/logout/', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST':
        logout_user()
        return redirect(url_for('auth.login'))
    return render_template('/blog/logout.html')


ALLOWED_EXTENSIONS = set(["png", "jpg", "jpeg", "gif"])


def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@auth.route("/upload_image", methods=['GET', 'POST'])
def upload_image():
    if request.method == "POST":
        print(request.files)
        file = request.files['image']
        if file.filename == '':
            flash('No selected file')
            return redirect(url_for('auth.create'))
        if file and allowed_file(file.filename):
            # if image with same name exists
            if os.path.exists('static/img/blog' + '/' + file.filename):
                _dot = file.filename.find(".")
                file.filename = file.filename[:_dot] + \
                    str(uuid.uuid4()) + file.filename[_dot:]
            filename = secure_filename(file.filename)
            file.save(os.path.join('static/img/blog', filename))
            return file.filename


@auth.route("/blog")
def blog():
    posts = Blogpost.query.all()
    return render_template('/blog/blog.html', posts=posts, user=current_user)


@auth.route('/blog/drafts/')
def drafts():
    posts = Blogpost.query.filter_by(published=False).all()
    return render_template('/blog/blog.html', posts=posts, drafts=True)


@auth.route('/blog/create/', methods=['GET', 'POST'])
def create():
    return render_template('/blog/create.html')


@auth.route('/blog/addpost', methods=['POST'])
def addpost():
    title = request.form.get('title')
    content = request.form.get('content')
    published = request.form.get('published')
    if published == 'y':
        published = True
    else:
        published = False

    slug = re.sub(r'[^\w]+', '-', title.lower()).strip('-')

    post = Blogpost(title=title, content=content, published=published,
                    date_posted=datetime.now(), slug=slug)

    db.session.add(post)
    db.session.commit()

    return redirect(url_for('auth.blog'))


@auth.route('/blog/delete/<slug>/')
def delete(slug):
    post_to_delete = Blogpost.query.filter_by(slug=slug).first_or_404()

    try:
        db.session.delete(post_to_delete)
        db.session.commit()
        return redirect(url_for('auth.blog'))
    except:
        flash('There was an error deleting this post', category='error')

    return render_template('/blog/blog.html')


@auth.route('/blog/<slug>/')
def detail(slug):
    post = Blogpost.query.filter_by(slug=slug).first_or_404()
    date_posted = post.date_posted.strftime('%B %d, %Y')
    return render_template('/blog/detail.html', post=post, date_posted=date_posted)


@auth.route('/blog/<slug>/edit/', methods=['GET', 'POST'])
#@login_required
def edit(slug):
    post = Blogpost.query.filter_by(slug=slug).first_or_404()

    if request.method == 'POST':

        post.title = request.form.get('title')
        post.content = request.form.get('content')
        published = request.form.get('published')
        slug = re.sub(r'[^\w]+', '-', post.title.lower()).strip('-')
        post.slug = slug

        if published == 'y':
            published = True
        else:
            published = False
        post.published = published

        db.session.commit()
        return render_template('/blog/detail.html', post=post)

    return render_template('/blog/edit.html', post=post)

website/views.py
from flask import (Blueprint, Response,  url_for, redirect, render_template)

views = Blueprint('views', __name__)

@views.route("/")
def home():
    return render_template("index.html")

@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/contact")
def contact():
    return render_template("contact.html")

@views.route("/admin")
def admin():
    return redirect(url_for("home"))

@views.route("/portfolio")
def portfolio():
    return redirect(url_for("home"))

@views.route(404)
def not_found():
    return Response('<h3>Not found</h3>'), 404

website/templates/about.html
{% extends "base.html" %}
{% block title %} Home Page {% endblock %}
{% block content_title %} About Me {% endblock %}
{% block content %}
<section class="content">
  <div style="text-align: center;">
    <img src="/static/img/graduation1.jpg" class="img-fluid" style="width: 50%; padding-bottom: 10px;">
  </div>
  <div>I am an experienced engineering professional that has a passion for learning, and an aspiration to be the best version of myself 
    to help people solve problems and engage in meaningful discourse. I have a Bachelors degree from Monash University where I majored in Electrical
    and Computer Systems engineering. Through my work and my learnings at university I have developed a keen interest in different technologies, and
    it is a goal of mine to continue to always be a student at heart, and continue the learning process. I also learnt the importance of having an
    altruistic spirit, and it is a value that drives me.
  </div>
  <div><br></div>
  <div>
    <div>I consider myself a global citizen. This is because I've lived in 3 different continents across the world for
      almost equal amounts of time. I was born and raised in the USA, went to middle school in India, and finished high
      school and college in Australia.</div>
    <div><br></div>
    <div>
      <div>My interest in technology only developed during my latter years of University. I've always loved Physics since
        I was in school, but I disliked doing research for academic purposes, and so I wasn't sure what I wanted to do
        with my career even after I graduated from college. It was during the coronavirus crisis of 2020 that I discovered
        what my true interests were. I had the time and opportunity to explore various technologies and gain exposure to
        things that I had never used before, like Amazon Web Services. Becoming more proficient at programming, and
        learning more about computer science and how companies leverage hybrid cloud models is fascinating to me. At this
        point, I'm still uncertain as to where I want to take my career, but I've been given the opportunity to find out,
        and that's what I intend to do.</div>
      <div><br></div>
      <div>Right now I am continuing to learn, and work towards my goals, and this website is part of my journey. Outside
        of professional development, I love playing games with friends, and I also enjoy reading manga (One Piece!!). I am
        also an avid watcher of the NBA, and love to go to the gym to keep my fitness levels up.</div>
    </div>
  </div>
</section>
{% endblock %}

website/templates/base.html
<!doctype html5>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/site.css">
    <link rel="stylesheet" href="/static/css/fa.css">
    
    <!-- <script src="{{ url_for('static', filename='js/jquery-1.11.0.min.js') }}" type="text/javascript"></script> !-->

    <title>{% block title %} {% endblock %}</title>

</head>

<body>

    <!-- Bootstrap Navigation Bar-->

      <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/" style="color: deeppink; text-decoration: none;">Nihal Noor</a>
          {% block blognav %} {% endblock %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/blog">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Portfolio</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
  <main class="container-fluid page-background" role="main">
      {% block background %} {% endblock %}

    <div class="container">
        {% block page_header %}
        <div id="page-header" class="text-center">
          <h1>{% block content_title %}{% endblock %}</h1>
        </div>
        {% endblock %}
        {% block content %} {% endblock %} 
    </div>
      {% block homepage %} {% endblock %}
  </main>
    
  <footer class="text-center fixed-bottom text-white bg-dark footer">

    <div class="row">
      <div class="col-sm-12 text-center p-2_5">
        © 2021 — Nihal Noor All Rights Reserved. Powered by 
        <a href="https://flask.palletsprojects.com/en/2.0.x/" style="color: deeppink; text-decoration: none;" target="_blank">Flask</a> and 
        <a href="https://getbootstrap.com/" style="color:deeppink; text-decoration: none;" target="_blank">Bootstrap</a>
      </div>  
    </div>
      
  </footer>

    <!-- Boostrap Bundle with Popper-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="/static/js/bootstrap.js"></script>
</body>
</html>

website/templates/blog-base.html
<!doctype html5>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/site.css">
    <link rel="stylesheet" href="/static/css/fa.css">
    

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>

</head>

<body>

    <!-- Bootstrap Navigation Bar-->
    

      <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/blog">Nihal</a>
          {% block blognav %} {% endblock %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/blog">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Portfolio</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
      {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
          {% for category, message in messages %} 
            {% if category == 'error' %}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
              {% endif %} 
          {% endfor %} 
        {% endif %} 
      {% endwith %}
          
<main class="page-background container-fluid" role="main">
      {% block background %} {% endblock %}

    <div class="card-container content-blog">
      <div class="card">
        {% block page_header %}
        <div class="card-header bg-dark text-white">
          <h1>{% block content_title %}{% endblock %}</h1>
        </div>
        {% endblock %}
        <div class="card-body">
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>
</main>

  <div class="text-center fixed-bottom text-white bg-dark footer">

    <div class="row">
      <div class="col-md-12 text-center p-3">
        © 2021 — Nihal Noor All Rights Reserved. Powered by 
        <a href="https://flask.palletsprojects.com/en/2.0.x/" style="color: deeppink; text-decoration: none;" target="_blank">Flask</a> and 
        <a href="https://getbootstrap.com/" style="color:deeppink; text-decoration: none;" target="_blank">Bootstrap</a>
      </div>  
    </div>
      
  </div>


 <!-- Boostrap Bundle with Popper-->
  <script src="/static/js/bootstrap.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
</body>
</html>

website/templates/blog/blog.html
{% extends "blog-base.html" %}
{% block title %} Blog Entries {% endblock %}

{% block blognav %} 
<div class="navbar-collapse collapse justify-content-start">
  <ul class="navbar-nav mr-auto">
    {% if current_user.is_authenticated %}
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.drafts') }}">Drafts</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.create') }}">Create Entry</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a></li>
    {% endif %}
    </ul>
</div>
{% endblock %}

{% block content_title %}{% if search %}Search "{{ search }}"{% else %}Blog Entries{% endif %}{% endblock %}

{% block content %}
  {% for post in posts[::-1] %}
    {% if drafts %}
      <h3>
        <a href="{% if not post.published %} {{ url_for('auth.edit', slug=post.slug) }}{% endif %}" style="color: black; text-decoration: none;">
          {{ post.title }}
        </a>
      </h3>
      <p style="font-size: small;">Created {{ post.date_posted.strftime('%B %d, %Y') }}</p>  
    {% else %}
      {% if post.published %}
      <h3>
        <a href="{% if post.published %}{{ url_for('auth.detail', slug=post.slug) }} {% endif %}" style="color: black; text-decoration: none;">
          {{ post.title}}
        </a>
      </h3>
      <p style="font-size: small;">Created {{ post.date_posted.strftime('%B %d, %Y') }}</p>
      <a>
        {{post.content|striptags|truncate(200) | safe}}
      </a>
      <p class="quiet" style="text-align: right; font-size: small;"><a href="/blog/{{post.slug}}">Read more...</a></p>
      <hr>
      {% endif %}
    {% endif %}
    
  {% else %}
    <p>No entries have been created yet.</p>
  {% endfor %}
{% endblock %}

website/templates/blog/create.html
{% extends "blog-base.html" %}

{% block title %}Create entry{% endblock %}

{% block content_title %}Create entry{% endblock %}

{% block content %}
<form action="{{ url_for('auth.addpost') }}" class="form-horizontal" method="post">
  <div class="form-group">
    <label for="title" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
      <input class="form-control" id="title" name="title" type="text">
    </div>
  </div>
  <div class="form-group">
    <label for="Content" class="col-sm-2 control-label">Content</label>
    <div class="col-sm-10">
      <textarea class="form-control" id="summernote" name="content"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input name="published" type="checkbox" value="y" checked="checked"> Published?
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button class="btn btn-primary" type="submit">Create</button>
      <a class="btn btn-default" href="{{ url_for('auth.blog') }}">Cancel</a>
    </div>
  </div>
</form>

<script>
$(document).ready(function() {
    $('#summernote').summernote({
      placeholder: 'Write here',
      tabsize: 2,
      height: 300,
      minHeight: null,
      maxHeight: null,
      callbacks: {
        onImageUpload: function(image) {
          uploadImage(image[0]);
        }
      }
    });
});

function uploadImage(image) {
  var data = new FormData();
  data.append("image", image);
  $.ajax({
      url: "/upload_image",
      cache: false,
      contentType: false,
      processData: false,
      data: data,
      type: "POST",
      success: function(filename) {
          var image = $('<img>').attr('src', '/static/img/' + filename).addClass("img-fluid");
          $('#summernote').summernote("insertNode", image[0]);
      },
      error: function(data) {
          console.log(data);
      }
  });
}
</script>
{% endblock %}

website/templates/blog/detail.html
{% extends "blog-base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content_title %}{{ post.title }}{% endblock %}

{% block blognav %} 
<div class="navbar-collapse collapse justify-content-start">
  <ul class="navbar-nav mr-auto">
    {% if current_user.is_authenticated %}
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.drafts') }}">Drafts</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.create') }}">Create Entry</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.edit', slug=post.slug) }}">Edit entry</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a></li>
    {% endif %}  
  </ul>
</div>
{% endblock %}

{% block content %}
  <p style="font-size: medium;">Created {{ date_posted }}</p>
  {{ post.content | safe}}
{% endblock %}

website/templates/blog/edit.html
{% extends "blog-base.html" %}

{% block title %}Edit entry{% endblock %}

{% block content_title %}Edit entry{% endblock %}

{% block blognav %} 
<div class="navbar-collapse collapse justify-content-start">
  <ul class="navbar-nav mr-auto">
    {% if current_user.is_authenticated %}
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.drafts') }}">Drafts</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.create') }}">Create Entry</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a></li>
    {% endif %}  
  </ul>
</div>
{% endblock %}

{% block content %}
  <form action="{{ url_for('auth.edit', slug=post.slug) }}" class="form-horizontal" method="POST">
    <div class="form-group">
      <label for="title" class="col-sm-2 control-label">Title</label>
      <div class="col-sm-10">
        <input class="form-control" id="title" name="title" type="text" value="{{ request.form.get('title',post.title) }}">
      </div>
    </div>
    <div class="form-group">
      <label for="Content" class="col-sm-2 control-label">Content</label>
      <div class="col-sm-10">
        <textarea class="form-control" id="summernote" name="content" style="height: 300px;">{{ request.form.get('content', post.content) }}</textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <label>
            <input {% if post.published %}checked="checked" {% endif %}name="published" type="checkbox" value="y"> Published?
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Save</button>
        <a href="/blog/delete/{{post.slug}}" class="btn btn-danger" type="submit" onclick="return confirm('Do you want to delete this post?')"> Delete </button>
        <a class="btn btn-default" href="{{ url_for('auth.blog') }}">Cancel</a>
      </div>
    </div>
  </form>

<script>
$(document).ready(function() {
    $('#summernote').summernote({
      placeholder: 'Write here',
      tabsize: 2,
      height: 300,
      minHeight: null,
      maxHeight: null,
      callbacks: {
        onImageUpload: function(image) {
          uploadImage(image[0]);
        }
      }
    });
});

function uploadImage(image) {
  var data = new FormData();
  data.append("image", image);
  $.ajax({
      url: "/upload_image",
      cache: false,
      contentType: false,
      processData: false,
      data: data,
      type: "POST",
      success: function(filename) {
          var image = $('<img>').attr('src', '/static/img/blog/' + filename).addClass("img-fluid");
          $('#summernote').summernote("insertNode", image[0]);
      },
      error: function(data) {
          console.log(data);
      }
  });
}
</script>
  
{% endblock %}

website/templates/blog/login.html
{% extends "blog-base.html" %}

{% block title %}Log in{% endblock %}

{% block content_title %}Log in{% endblock %}

{% block content %}

  <form action="{{ url_for('auth.login') }}" class="form-horizontal" method="POST">
    <div class="form-group">
      <label for="username" class="col-sm-2 control-label">Username</label>
      <div class="col-sm-10">
        <input class="form-control" id="username" name="username" type="username" placeholder="Enter username">
      </div>
    </div>
    <div class="form-group">
      <label for="password" class="col-sm-2 control-label">Password</label>
      <div class="col-sm-10">
        <input class="form-control" id="password" name="password" type="password" placeholder="Enter password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Log in</button>
      </div>
    </div>
  </form>
{% endblock %}

website/templates/blog/logout.html
{% extends "blog-base.html" %}

{% block title %}Log out{% endblock %}

{% block content_title %}Log out{% endblock %}

{% block content %}
  <p>Click the button below to log out of the site.</p>
  <form action="{{ url_for('auth.logout') }}" class="form-horizontal" method="post">
    <button class="btn btn-primary" type="submit">Log out</button>
  </form>
{% endblock %}

website/templates/blog/signup.html
{% extends "blog-base.html" %}

{% block title %} Sign Up {% endblock %}

{% block content_title %}Sign Up{% endblock %}

{% block content %}
  <form action="{{ url_for('auth.signup') }}" class="form-horizontal" method="POST">
    <div class="form-group">
      <label for="username" class="col-sm-2 control-label">Username</label>
      <div class="col-sm-10">
        <input class="form-control" id="username" name="username" type="username" placeholder="Enter username">
      </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
          <input class="form-control" id="password" name="password" type="password" placeholder="Enter password">
        </div>
      </div>
      <div class="form-group">
        <label for="password2" class="col-sm-2 control-label">Password (Confirm)</label>
        <div class="col-sm-10">
          <input class="form-control" id="password2" name="password2" type="password" placeholder="Confirm password">
        </div>
      </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Sign Up</button>
      </div>
    </div>
  </form>
{% endblock %}

website/templates/contact.html
{% extends "base.html" %}
{% block title %} Contact Me {% endblock %}
{% block content %}
<div class='content'>
  <p>This page will have links to my social media</p>
  <p>This includes: Github, Twitter, Email, LinkedIn</p>
</div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% block title %} Home Page {% endblock %}
{% block background %} 
{% endblock %}

{% block homepage %}
 
<div class="background container-fluid">
  <div class="container">
    <div class="row h-100 align-items-center">
      <div class="col-md-12 text-center">
        <h1 class="fst-italic headline">Nihal Noor</h1>
        <h3 class="headline">Aspiring DevOps Engineer</h3>
        <div class="social">
          <ul class="social">
            <li style="padding-right: 0.5em;">
              <a href="https://www.linkedin.com/in/nihal-noor/" target="_blank">
                <i class="fab fa-linkedin fa-3x"></i>
              </a>
            </li>
            <li>
              <a href="https://www.github.com/lahinroon" target="_blank"> <i class="fab fa-github fa-3x"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

website/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1 {
            color: rgb(7, 21, 212);
            background-color: crimson;
        }
        p {
            color: darkgreen;
            background-color: darkgrey;
            margin: 25px;
            border: solid 1px darkorange;
        }
        .columns {
            border: solid 1px rgb(28, 25, 204);
            display: flex;
        }
        .columns > div {
            border: solid 1px #ddd;
            flex: 1; 
        }
    </style>
</head>
<body>
    <div class="columns">
        <div>Column 1</div>
        <div>Column 2</div>
        <div>Column 3</div>
    </div>
</body>
</html>